trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: PrintStage
  jobs:
  - template: templates/template.yml  # Reference the template here
    parameters:
      message: 'This is a custom message from the pipeline!'
