# pipe.yaml
trigger:
  branches:
    include:
      - main  # The branch that triggers this pipeline

pool:
  vmImage: 'windows-latest'

stages:
- stage: PrintStage
  jobs:
  - template: template.yaml  # Reference the template here
    parameters:
      message: 'This is a custom message from the pipeline!'
