trigger: none
pool:
  vmImage: 'windows-latest'
parameters:
  - name: rithvar1
    type: string
  - name: rithvar2
    type: string
steps:
  - script: |
      echo "Helo Rithwik this pipeline is trggered by 1st one"
      echo "Variable 1: ${{ parameters.rithvar1 }}"
      echo "variable 2: ${{ parameters.rithvar2 }}"
