trigger: none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: rivar1
    type: string
    default: ''
  - name: rivar2
    type: string
    default: ''

steps:
  - script: |
      echo "Helo Rithwik this pipeline is trggered by 1st one"
      echo "Variable 1: ${{ parameters.rivar1 }}"
      echo "variable 2: ${{ parameters.rivar2 }}"
