trigger:
- main

pool:
  vmImage: 'windows-latest'  # Use a Windows agent

steps:
  - script: |
      echo "Hello Rithwik, I am setting varaibles"
      echo "##vso[task.setvariable variable=rithvar1]12345"
      echo "##vso[task.setvariable variable=rithvar2]67890"
    name: SetVariables

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $rithvar1 = "${env:rithvar1}"
        $rithvar2 = "${env:rithvar2}"
        $uri = "https://dev.azure.com/v-scheedella/MT%20Stack%20Overflow/_apis/pipelines/21/runs?api-version=6.0-preview.1"
        $body = @{
          resources = @{
            repositories = @{
              self = @{
                refName = "refs/heads/main"
              }
            }
          }
          templateParameters = @{
            rithvar1 = $rithvar1
            rithvar2 = $rithvar2
          }
        } | ConvertTo-Json -Depth 10
        $headers = @{
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          "Content-Type" = "application/json"
        }
        Write-Host "Triggering second pipeline..."
        Write-Host "URI: $uri"
        Write-Host "Body: $body"
        Write-Host "Headers: $headers"
        $response = Invoke-RestMethod -Uri $uri -Method Post -Body $body -Headers $headers
        Write-Host "Response: $($response | ConvertTo-Json -Depth 10)"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      rithvar1: $(rithvar1)
      rithvar2: $(rithvar2)
