resources:
  repositories:
    - repository: testrepo
      type: github
      name: Rithwik-Bojja/Test
      endpoint: GitHubConnection


stages:
  - stage: Test
    jobs:
      - job: RunScript
        steps:
          - template: templates/my-template.yaml@mytemplates
