trigger: none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: ri_var1
    type: string
    default: ''
  - name: ri_var2
    type: string
    default: ''

steps:
  - script: |
      echo "This pipeline was triggered by the first pipeline."
      echo "Variable 1: ${{ parameters.ri_var1 }}"
      echo "variable 2: ${{ parameters.ri_var2 }}"
