trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Setting variables"
      echo "##vso[task.setvariable variable=testSuiteId]12345"
      echo "##vso[task.setvariable variable=testCaseId]67890"
    name: SetVariables

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $testSuiteId = "${env:testSuiteId}"
        $testCaseId = "${env:testCaseId}"
        $uri = "https://dev.azure.com/v-scheedella/MT%20Stack%20Overflow/_apis/pipelines/44/runs?api-version=6.0-preview.1"
        $body = @{
          resources = @{
            repositories = @{
              self = @{
                refName = "refs/heads/main"
              }
            }
          }
          templateParameters = @{
            testSuiteId = $testSuiteId
            testCaseId = $testCaseId
          }
        } | ConvertTo-Json -Depth 10
        $headers = @{
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          "Content-Type" = "application/json"
        }
        Write-Host "Triggering second pipeline..."
        Write-Host "URI: $uri"
        Write-Host "Body: $body"
        Write-Host "Headers: $headers"
        Invoke-RestMethod -Uri $uri -Method Post -Body $body -Headers $headers
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      testSuiteId: $(testSuiteId)
      testCaseId: $(testCaseId)
