trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
  - script: |
      echo "Hello Rithwik, I am setting varaibles"
      echo "##vso[task.setvariable variable=rith_var_1]007"
      echo "##vso[task.setvariable variable=rith_var_2]008"
    name: SetVariables

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $r = "${env:rith_var_1}"
        $r1 = "${env:rith_var_2}"
        $r_uri = "https://dev.azure.com/v-scheedella/MT%20Stack%20Overflow/_apis/pipelines/21/runs?api-version=6.0-preview.1"
        $rb = @{
          resources = @{
            repositories = @{
              self = @{
                refName = "refs/heads/main"
              }
            }
          }
          templateParameters = @{
            ri_var1 = $r
            ri_var2 = $r1
          }
        } | ConvertTo-Json -Depth 10
        $ri_h = @{
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          "Content-Type" = "application/json"
        }
        Invoke-RestMethod -Uri $r_uri -Method Post -Body $rb -Headers $ri_h
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
       ri_var1: $(rith_var_1)
       ri_var2: $(rith_var_2)
