trigger:
- main

pool:
  vmImage: 'windows-latest' 

steps:
  - script: |
      echo "Hello Rithwik, I am setting varaibles"
      echo "##vso[task.setvariable variable=rithvar1]007"
      echo "##vso[task.setvariable variable=rithvar2]008"
    name: RithSetVariables

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $rithvar1 = "${env:rithvar1}"
        $rithvar2 = "${env:rithvar2}"
        $rurl = "https://dev.azure.com/v-scheedella/MT%20Stack%20Overflow/_apis/pipelines/21/runs?api-version=6.0-preview.1"
        $rb = @{
          resources = @{
            repositories = @{
              self = @{
                refName = "refs/heads/main"
              }
            }
          }
          templateParameters = @{
            rithvar1 = $rithvar1
            rithvar2 = $rithvar2
          }
        } | ConvertTo-Json -Depth 10
        $rh = @{
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          "Content-Type" = "application/json"
        }
        Invoke-RestMethod -Uri $rurl -Method Post -Body $rb -Headers $rh
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      rithvar1: $(rithvar1)
      rithvar2: $(rithvar2)
